### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by fidesachates** [RobertD502/cowayaio#1]
Hi,

I was using your pyiocare package, but you seem to have deleted and I assume it was in favor of this package? I can't seem to get this to work. The login method is just throwing `Coway API authentication error: unable to retrieve auth code. Likely due to invalid username/password.`, but I've assured my auth credentials is correct by using the password to login to the website https://idp.coway.com/front/login_select

idk if it matters (as I can't even log in), but I have a AIRMEGA AP-1512HHS.

**Comment by RobertD502** [comment]
Is this for home assistant?

**Comment by fidesachates** [comment]
> Is this for home assistant?

No, just a home spun server I whipped up to get metrics for my prometheus / grafana

**Comment by fidesachates** [comment]
Python 3.10
cowayaio==0.1.4

```
import asyncio
from cowayaio import CowayClient


async def login():
    client = CowayClient('eyy2102@gmail.com', 'zngk.4CUfFx2')
    await client.login()


if __name__ == '__main__':
    asyncio.run(login())
```

> Traceback (most recent call last):
  File "test.py", line 20, in <module>
    asyncio.run(login())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "test.py", line 8, in login
    await client.login()
  File "venv/lib/python3.10/site-packages/cowayaio/coway_client.py", line 43, in login
    auth_code = await self._get_auth_code(login_url, cookies)
  File "venv/lib/python3.10/site-packages/cowayaio/coway_client.py", line 74, in _get_auth_code
    raise AuthError(f'Coway API authentication error: unable to retrieve auth code. Likely due to invalid username/password.')
cowayaio.exceptions.AuthError: Coway API authentication error: unable to retrieve auth code. Likely due to invalid username/password.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9c22688be0>

**Comment by RobertD502** [comment]
Ah. Use this library instead. Coway, as of last week, required all accounts to be moved to a coway account and the login method changed which cowayaio has been modified to use.

**Comment by RobertD502** [comment]
> Python 3.10
> 
> cowayaio==0.1.4
> 
> 
> 
> ```
> 
> import asyncio
> 
> from cowayaio import CowayClient
> 
> 
> 
> 
> 
> async def login():
> 
>     client = CowayClient('eyy2102@gmail.com', 'zngk.4CUfFx2')
> 
>     await client.login()
> 
> 
> 
> 
> 
> if __name__ == '__main__':
> 
>     asyncio.run(login())
> 
> ```
> 
> 
> 
> > Traceback (most recent call last):
> 
>   File "test.py", line 20, in <module>
> 
>     asyncio.run(login())
> 
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
> 
>     return future.result()
> 
>   File "test.py", line 8, in login
> 
>     await client.login()
> 
>   File "venv/lib/python3.10/site-packages/cowayaio/coway_client.py", line 43, in login
> 
>     auth_code = await self._get_auth_code(login_url, cookies)
> 
>   File "venv/lib/python3.10/site-packages/cowayaio/coway_client.py", line 74, in _get_auth_code
> 
>     raise AuthError(f'Coway API authentication error: unable to retrieve auth code. Likely due to invalid username/password.')
> 
> cowayaio.exceptions.AuthError: Coway API authentication error: unable to retrieve auth code. Likely due to invalid username/password.
> 
> Unclosed client session
> 
> client_session: <aiohttp.client.ClientSession object at 0x7f9c22688be0>
> 
> 
> 
> 

Have you migrated your account over yet using Coway's mobile app?

**Comment by fidesachates** [comment]
> Have you migrated your account over yet using Coway's mobile app?

Sigh.... thank you. This resolved it I believe. Hadn't opened the app in almost a year thanks to my service using your app so I had no idea. Bless you for the fast response. Much appreciated sir.

**Comment by RobertD502** [comment]
No problem!
