### ISSUE TITLE
Suggestion: restore pyiocare and archive it to fix broken link in pypi

### ISSUE THREAD

**Issue by fidesachates** [RobertD502/cowayaio#2]
For anyone like myself who was using pyiocare, I was very confused and concerned when the [pypi page](https://pypi.org/project/pyiocare/) linked to a broken link. I understand that you're no longer supporting it, but maybe restoring it, archiving it, and updating the readme to point this repo would help out other people. 

Thanks again for your work here!

**Comment by RobertD502** [comment]
Done.
