### ISSUE TITLE
Password expired?

### ISSUE THREAD

**Issue by fidesachates** [RobertD502/cowayaio#4]
Do you know what this password expired error message is? I was able to log into coway's website and got no notification of any password expiration. I set skip_password_change to true which removed the error and I was able to continue so I don't have any issues, but I was wondering if there was more context here and if this was going to bite me later.

**Comment by RobertD502** [comment]
Coway started informing users that their password hasn't been changed in 60 days or more with options to skip password change for now or to change your password. As a result, this message caused the login process to break. To get around this, I gave the option for users to select the skip password change option during login. The only caveat is that if you select the skip password option, whenever you login again, it will once again ask you to change your password or to skip changing your password. It is more of an annoyance by Coway than anything. It will not bite you later to have the skip password option enabled.

The only other choice is to manually go change your password in the app, but the message will come back again in 60 or so days.
